sudo: false
language: node_js
branches:
  only:
    - master
node_js:
   - "4"
   - "5"
os:
  - linux

deploy:
  provider: npm
  email: lamo2k123@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: lamo2k123/monocules.ws